import { X, Loader2 } from "lucide-react";

interface Props {
  open: boolean;
  onClose: () => void;
  qr: string | null;
  code: string;
  setCode: (val: string) => void;
  onVerify: () => void;
  loading: boolean;
}

export function TwoFAModal({
  open,
  onClose,
  qr,
  code,
  setCode,
  onVerify,
  loading,
}: Props) {
  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4">
      <div className="bg-white w-full max-w-3xl rounded-2xl shadow-lg overflow-hidden">
        
        {/* HEADER */}
        <div className="flex justify-between items-center p-4 border-b">
          <h3 className="font-semibold text-lg">Enable Two-Factor Authentication</h3>
          <button onClick={onClose}>
            <X />
          </button>
        </div>

        {/* BODY */}
        <div className="grid md:grid-cols-2">
          
          {/* LEFT - QR */}
          <div className="flex items-center justify-center p-6 bg-gray-50">
            {qr ? (
              <img
                src={`data:image/png;base64,${qr}`}
                className="w-48 h-48"
              />
            ) : (
              <Loader2 className="animate-spin" />
            )}
          </div>

          {/* RIGHT - STEPS */}
          <div className="p-6 space-y-4">
            <div>
              <p className="font-medium">Step 1</p>
              <p className="text-sm text-gray-500">
                Scan the QR code using Google Authenticator
              </p>
            </div>

            <div>
              <p className="font-medium">Step 2</p>
              <p className="text-sm text-gray-500">
                Enter the 6-digit code generated by the app
              </p>
            </div>

            <input
              type="text"
              placeholder="123456"
              value={code}
              onChange={(e) => setCode(e.target.value)}
              className="border rounded-lg p-3 w-full text-center tracking-widest text-lg"
            />

            <button

              onClick={onVerify}
              disabled={loading || code.length !== 6}
              className="w-full bg-primary text-white py-2 rounded-lg flex items-center justify-center gap-2"
            >
              {loading && <Loader2 className="animate-spin" size={16} />}
              Verify & Activate
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}